-- Devirtualized with Luraph v14.8 engine

local connection = game.DescendantAdded:Connect(function(descendant)
end)
connection:Disconnect()
local connection2 = workspace.DescendantAdded:Connect(function(descendant2)
end)
connection2:Disconnect()
local connection3 = Folder.DescendantAdded:Connect(function(descendant3)
end)
connection3:Disconnect()
local connection4 = Folder2.DescendantAdded:Connect(function(descendant4)
end)
connection4:Disconnect()
local HttpService = game:GetService("HttpService")
local connection5 = HttpService.DescendantAdded:Connect(function(descendant5)
end)
connection5:Disconnect()
local RunService = game:GetService("RunService")
local connection6 = RunService.DescendantAdded:Connect(function(descendant6)
end)
connection6:Disconnect()
